import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<Toaster position="top-center" reverseOrder={false} />
			<body className={( "dark:bg-gray-900")}>{children}</body>
		</html>
	);
}
